# .github/workflows/publish.yml

name: Publish to PyPI

# --- Trigger ---
# This workflow runs only when you create and push a tag that starts with 'v'
# For example: v0.0.1, v0.1, v1.2.3
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    # --- Job Environment ---
    runs-on: ubuntu-latest

    steps:
      # --- 1. Check out the repository code ---
      - name: Check out code
        uses: actions/checkout@v4

      # --- 2. Set up Python ---
      # We only need one version of Python to build and publish.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # --- 3. Install build tools ---
      - name: Install build dependencies
        run: python -m pip install --upgrade build twine

      # --- 4. Build the package ---
      # This creates the sdist and wheel files in a 'dist/' directory.
      - name: Build package
        run: python -m build

      # --- 5. Publish to PyPI ---
      # This action securely uploads the contents of 'dist/' to PyPI.
      # It uses the secret token you created earlier.
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}